### ISSUE TITLE
Add Intake based on current limit

### ISSUE THREAD

**Issue by aswerdlow935** [themilkenknights/MilkenKnights-PowerUp#14]
Run intake rollers until current limit is reached then change arm setpoint.

**Comment by AustinShalit** [comment]
Make sure to add a delay to ensure starting spikes are not interpreted as ready.

**Comment by aswerdlow935** [comment]
When you say starting spikes do you mean directly after teleop/auto enable?

**Comment by AustinShalit** [comment]
I mean when the intake rollers start.  Starting a motor draws a lot of current.

**Comment by aswerdlow935** [comment]
Drive Team vetoed idea

**Comment by alexanderswerdlow** [comment]
Currently debugging pdp to access current output over CAN. Plan to use the current to signal the driver.

**Comment by AustinShalit** [comment]
Be careful when doing this... there is a difference between grabbing a cube and having a cube.  I still recommend a detected sensor to do this.
